import type { Metadata } from 'next';
import { Inter, Syne } from 'next/font/google';
import './globals.css';
import { Header } from '@/app/_assets/Header';
import styles from './styles.module.css';

const inter = Inter({ subsets: ['latin'] });
const syne = Syne({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${syne.className} ${styles.grain} w-full overflow-x-hidden bg-[#1f1f1f]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
